/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedHubIndexRouteImport } from './routes/_authenticated/hub.index'
import { Route as AuthenticatedHubProfileRouteImport } from './routes/_authenticated/hub.profile'
import { Route as AuthenticatedHubLeaderboardRouteImport } from './routes/_authenticated/hub.leaderboard'
import { Route as AuthenticatedHubGamesTriviaBlitzRouteImport } from './routes/_authenticated/hub.games.trivia-blitz'
import { Route as AuthenticatedHubGamesSemanticRouteImport } from './routes/_authenticated/hub.games.semantic'
import { Route as AuthenticatedHubGamesPingPongRouteImport } from './routes/_authenticated/hub.games.ping-pong'
import { Route as AuthenticatedHubGamesPaintAndGuessRouteImport } from './routes/_authenticated/hub.games.paint-and-guess'
import { Route as AuthenticatedHubGamesChessRouteImport } from './routes/_authenticated/hub.games.chess'
import { Route as AuthenticatedHubGamesBalderdashRouteImport } from './routes/_authenticated/hub.games.balderdash'
import { Route as AuthenticatedHubGamesSlugRouteImport } from './routes/_authenticated/hub.games.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubIndexRoute = AuthenticatedHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHubRoute,
} as any)
const AuthenticatedHubProfileRoute = AuthenticatedHubProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedHubRoute,
} as any)
const AuthenticatedHubLeaderboardRoute =
  AuthenticatedHubLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesTriviaBlitzRoute =
  AuthenticatedHubGamesTriviaBlitzRouteImport.update({
    id: '/games/trivia-blitz',
    path: '/games/trivia-blitz',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesSemanticRoute =
  AuthenticatedHubGamesSemanticRouteImport.update({
    id: '/games/semantic',
    path: '/games/semantic',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesPingPongRoute =
  AuthenticatedHubGamesPingPongRouteImport.update({
    id: '/games/ping-pong',
    path: '/games/ping-pong',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesPaintAndGuessRoute =
  AuthenticatedHubGamesPaintAndGuessRouteImport.update({
    id: '/games/paint-and-guess',
    path: '/games/paint-and-guess',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesChessRoute =
  AuthenticatedHubGamesChessRouteImport.update({
    id: '/games/chess',
    path: '/games/chess',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesBalderdashRoute =
  AuthenticatedHubGamesBalderdashRouteImport.update({
    id: '/games/balderdash',
    path: '/games/balderdash',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)
const AuthenticatedHubGamesSlugRoute =
  AuthenticatedHubGamesSlugRouteImport.update({
    id: '/games/$slug',
    path: '/games/$slug',
    getParentRoute: () => AuthenticatedHubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hub': typeof AuthenticatedHubRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/hub/leaderboard': typeof AuthenticatedHubLeaderboardRoute
  '/hub/profile': typeof AuthenticatedHubProfileRoute
  '/hub/': typeof AuthenticatedHubIndexRoute
  '/hub/games/$slug': typeof AuthenticatedHubGamesSlugRoute
  '/hub/games/balderdash': typeof AuthenticatedHubGamesBalderdashRoute
  '/hub/games/chess': typeof AuthenticatedHubGamesChessRoute
  '/hub/games/paint-and-guess': typeof AuthenticatedHubGamesPaintAndGuessRoute
  '/hub/games/ping-pong': typeof AuthenticatedHubGamesPingPongRoute
  '/hub/games/semantic': typeof AuthenticatedHubGamesSemanticRoute
  '/hub/games/trivia-blitz': typeof AuthenticatedHubGamesTriviaBlitzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hub/leaderboard': typeof AuthenticatedHubLeaderboardRoute
  '/hub/profile': typeof AuthenticatedHubProfileRoute
  '/hub': typeof AuthenticatedHubIndexRoute
  '/hub/games/$slug': typeof AuthenticatedHubGamesSlugRoute
  '/hub/games/balderdash': typeof AuthenticatedHubGamesBalderdashRoute
  '/hub/games/chess': typeof AuthenticatedHubGamesChessRoute
  '/hub/games/paint-and-guess': typeof AuthenticatedHubGamesPaintAndGuessRoute
  '/hub/games/ping-pong': typeof AuthenticatedHubGamesPingPongRoute
  '/hub/games/semantic': typeof AuthenticatedHubGamesSemanticRoute
  '/hub/games/trivia-blitz': typeof AuthenticatedHubGamesTriviaBlitzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/hub': typeof AuthenticatedHubRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/hub/leaderboard': typeof AuthenticatedHubLeaderboardRoute
  '/_authenticated/hub/profile': typeof AuthenticatedHubProfileRoute
  '/_authenticated/hub/': typeof AuthenticatedHubIndexRoute
  '/_authenticated/hub/games/$slug': typeof AuthenticatedHubGamesSlugRoute
  '/_authenticated/hub/games/balderdash': typeof AuthenticatedHubGamesBalderdashRoute
  '/_authenticated/hub/games/chess': typeof AuthenticatedHubGamesChessRoute
  '/_authenticated/hub/games/paint-and-guess': typeof AuthenticatedHubGamesPaintAndGuessRoute
  '/_authenticated/hub/games/ping-pong': typeof AuthenticatedHubGamesPingPongRoute
  '/_authenticated/hub/games/semantic': typeof AuthenticatedHubGamesSemanticRoute
  '/_authenticated/hub/games/trivia-blitz': typeof AuthenticatedHubGamesTriviaBlitzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/hub'
    | '/auth/callback'
    | '/hub/leaderboard'
    | '/hub/profile'
    | '/hub/'
    | '/hub/games/$slug'
    | '/hub/games/balderdash'
    | '/hub/games/chess'
    | '/hub/games/paint-and-guess'
    | '/hub/games/ping-pong'
    | '/hub/games/semantic'
    | '/hub/games/trivia-blitz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/hub/leaderboard'
    | '/hub/profile'
    | '/hub'
    | '/hub/games/$slug'
    | '/hub/games/balderdash'
    | '/hub/games/chess'
    | '/hub/games/paint-and-guess'
    | '/hub/games/ping-pong'
    | '/hub/games/semantic'
    | '/hub/games/trivia-blitz'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/hub'
    | '/auth/callback'
    | '/_authenticated/hub/leaderboard'
    | '/_authenticated/hub/profile'
    | '/_authenticated/hub/'
    | '/_authenticated/hub/games/$slug'
    | '/_authenticated/hub/games/balderdash'
    | '/_authenticated/hub/games/chess'
    | '/_authenticated/hub/games/paint-and-guess'
    | '/_authenticated/hub/games/ping-pong'
    | '/_authenticated/hub/games/semantic'
    | '/_authenticated/hub/games/trivia-blitz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub/': {
      id: '/_authenticated/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof AuthenticatedHubIndexRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/profile': {
      id: '/_authenticated/hub/profile'
      path: '/profile'
      fullPath: '/hub/profile'
      preLoaderRoute: typeof AuthenticatedHubProfileRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/leaderboard': {
      id: '/_authenticated/hub/leaderboard'
      path: '/leaderboard'
      fullPath: '/hub/leaderboard'
      preLoaderRoute: typeof AuthenticatedHubLeaderboardRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/trivia-blitz': {
      id: '/_authenticated/hub/games/trivia-blitz'
      path: '/games/trivia-blitz'
      fullPath: '/hub/games/trivia-blitz'
      preLoaderRoute: typeof AuthenticatedHubGamesTriviaBlitzRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/semantic': {
      id: '/_authenticated/hub/games/semantic'
      path: '/games/semantic'
      fullPath: '/hub/games/semantic'
      preLoaderRoute: typeof AuthenticatedHubGamesSemanticRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/ping-pong': {
      id: '/_authenticated/hub/games/ping-pong'
      path: '/games/ping-pong'
      fullPath: '/hub/games/ping-pong'
      preLoaderRoute: typeof AuthenticatedHubGamesPingPongRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/paint-and-guess': {
      id: '/_authenticated/hub/games/paint-and-guess'
      path: '/games/paint-and-guess'
      fullPath: '/hub/games/paint-and-guess'
      preLoaderRoute: typeof AuthenticatedHubGamesPaintAndGuessRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/chess': {
      id: '/_authenticated/hub/games/chess'
      path: '/games/chess'
      fullPath: '/hub/games/chess'
      preLoaderRoute: typeof AuthenticatedHubGamesChessRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/balderdash': {
      id: '/_authenticated/hub/games/balderdash'
      path: '/games/balderdash'
      fullPath: '/hub/games/balderdash'
      preLoaderRoute: typeof AuthenticatedHubGamesBalderdashRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
    '/_authenticated/hub/games/$slug': {
      id: '/_authenticated/hub/games/$slug'
      path: '/games/$slug'
      fullPath: '/hub/games/$slug'
      preLoaderRoute: typeof AuthenticatedHubGamesSlugRouteImport
      parentRoute: typeof AuthenticatedHubRoute
    }
  }
}

interface AuthenticatedHubRouteChildren {
  AuthenticatedHubLeaderboardRoute: typeof AuthenticatedHubLeaderboardRoute
  AuthenticatedHubProfileRoute: typeof AuthenticatedHubProfileRoute
  AuthenticatedHubIndexRoute: typeof AuthenticatedHubIndexRoute
  AuthenticatedHubGamesSlugRoute: typeof AuthenticatedHubGamesSlugRoute
  AuthenticatedHubGamesBalderdashRoute: typeof AuthenticatedHubGamesBalderdashRoute
  AuthenticatedHubGamesChessRoute: typeof AuthenticatedHubGamesChessRoute
  AuthenticatedHubGamesPaintAndGuessRoute: typeof AuthenticatedHubGamesPaintAndGuessRoute
  AuthenticatedHubGamesPingPongRoute: typeof AuthenticatedHubGamesPingPongRoute
  AuthenticatedHubGamesSemanticRoute: typeof AuthenticatedHubGamesSemanticRoute
  AuthenticatedHubGamesTriviaBlitzRoute: typeof AuthenticatedHubGamesTriviaBlitzRoute
}

const AuthenticatedHubRouteChildren: AuthenticatedHubRouteChildren = {
  AuthenticatedHubLeaderboardRoute: AuthenticatedHubLeaderboardRoute,
  AuthenticatedHubProfileRoute: AuthenticatedHubProfileRoute,
  AuthenticatedHubIndexRoute: AuthenticatedHubIndexRoute,
  AuthenticatedHubGamesSlugRoute: AuthenticatedHubGamesSlugRoute,
  AuthenticatedHubGamesBalderdashRoute: AuthenticatedHubGamesBalderdashRoute,
  AuthenticatedHubGamesChessRoute: AuthenticatedHubGamesChessRoute,
  AuthenticatedHubGamesPaintAndGuessRoute:
    AuthenticatedHubGamesPaintAndGuessRoute,
  AuthenticatedHubGamesPingPongRoute: AuthenticatedHubGamesPingPongRoute,
  AuthenticatedHubGamesSemanticRoute: AuthenticatedHubGamesSemanticRoute,
  AuthenticatedHubGamesTriviaBlitzRoute: AuthenticatedHubGamesTriviaBlitzRoute,
}

const AuthenticatedHubRouteWithChildren =
  AuthenticatedHubRoute._addFileChildren(AuthenticatedHubRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHubRoute: typeof AuthenticatedHubRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHubRoute: AuthenticatedHubRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
